springdoc:
  pathsToMatch: /api/v1/**
  title: rest-api-tutorials
  version: v1
  description: Base project for REST API tutorials
  url: http://www.norulshahlam.com/
  name: Shah & Co
  email: norulshahlam@gmail.com
  license-name: License 30AP
  license-url: url
server:
  port: 9090
spring:
  application:
    profile: default
    name: rest-api-tutorials
    description: rest-api-tutorials
  banner:
    image:
      margin: 6
      invert: true
      height: 20
      pixelmode: TEXT
      bitdepth: 8
      width: 130
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Singapore
        format:
          sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS
scheduled:
  period:
    in-cron: 0 0 * ? * * # Every hour
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  profiles:
    active: dev

