spring:
  application:
    profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:banking
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console